<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-NetPulse.Worker-d051975e-1245-4539-9c4f-9fcbdb5ebe0f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetPulse.Infrastructure\NetPulse.Infrastructure.csproj" />
    <ProjectReference Include="..\NetPulse.Application\NetPulse.Application.csproj" />
  </ItemGroup>
</Project>
